### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by luqasz** [flydata/fluent-plugin-redshift#30]
Hi.

I'd like to know how does this plugin behaves when ingestion fails for some reason (eg. inserting 20 characters long string into varchar(10)). Does it move file to some other directory on S3 ?

**Comment by mmasashi** [comment]
Currently the plugin only reports an error without retry when getting a load error from Redshift. It doesn't move the files used for COPY.

**Comment by luqasz** [comment]
Ok. Thx for info. We rely on moving "broken" and ingested files over S3.
